name: CI

on: [push, pull_request]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    services:
      docker:
        image: docker:19.03.12
        options: --privileged
        ports:
          - 5000:5000
          - 9099:9099
          - 5001:5001
          - 8081:8081
          - 5002:5002
          - 9199:9199
          - 4000:4000
          - 4400:4400
          - 4500:4500
          - 9150:9150
          - 5007:5007

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Build and run Docker Compose
        run: docker-compose -f docker-compose.yml up --abort-on-container-exit --exit-code-from test

      - name: Check Docker Compose Test Result
        run: |
          EXIT_CODE=$(docker inspect test --format='{{.State.ExitCode}}')
          if [ "$EXIT_CODE" -ne 0 ]; then
            exit $EXIT_CODE
          fi
