name: GitGuardian scan

on:
  pull_request_target:
  push:
    branches:
      - main
      - develop # or any branches you want to scan on push

jobs:
  scanning:
    name: GitGuardian scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the PR source
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.sha }}
          repository: ${{ github.event.pull_request.head.repo.full_name }}

      - name: GitGuardian scan
        uses: GitGuardian/ggshield/actions/secret@v
