name: SonarCloud Issue Creator

on:
  workflow_run:
    workflows: ["Build"]
    types:
      - completed
    branches:
      - develop

jobs:
  create-issues:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests
          
      - name: Run SonarCloud to GitHub issue converter
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
        run: python sonarcloud_to_github.py 