name: Update Discord Roles

on:
  schedule:
    - cron: '0 0 * * *'  # Run daily at midnight
  workflow_dispatch:  # Allow manual trigger

jobs:
  update-roles:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r discord_bot/requirements.txt

      - name: Fetch GitHub contributions & update roles
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          TOKEN: ${{ secrets.DISCORD_BOT_TOKEN }}
        run: |
          cd discord_bot
          python fetch_contributors.py 
          python update_discord_roles.py